# Generated by Django 4.1.3 on 2022-11-28 16:44

from django.db import migrations, models
import django.db.models.deletion
import quantityfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branch", "0002_alter_branch_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("description", models.TextField()),
                (
                    "quantity",
                    quantityfield.fields.QuantityField(
                        base_units="gram", unit_choices=["gram"]
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="branch.branch",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
