# Generated by Django 4.1.3 on 2022-11-30 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_inventory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredient",
            options={},
        ),
    ]
