# Generated by Django 4.1.3 on 2022-11-28 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("branch", "0002_alter_branch_slug"),
        ("users", "0004_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="branch.branch",
            ),
        ),
    ]
